// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqzc751uxfED94lnq12o05wmCawxa0C-c',
    appId: '1:1068678823968:web:acccb3140d2f96eb747c45',
    messagingSenderId: '1068678823968',
    projectId: 'quizapp-2cba3',
    authDomain: 'quizapp-2cba3.firebaseapp.com',
    storageBucket: 'quizapp-2cba3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5XXg_9VEhjDSK0P1WTJW_s_KxXlJQU1s',
    appId: '1:1068678823968:android:becb9c2455ced178747c45',
    messagingSenderId: '1068678823968',
    projectId: 'quizapp-2cba3',
    storageBucket: 'quizapp-2cba3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOmv-HtfRKLijmZYBqBrR7eLUSNPlct-E',
    appId: '1:1068678823968:ios:18e7b60c5374d3b4747c45',
    messagingSenderId: '1068678823968',
    projectId: 'quizapp-2cba3',
    storageBucket: 'quizapp-2cba3.appspot.com',
    iosBundleId: 'com.example.firstAppEwa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOmv-HtfRKLijmZYBqBrR7eLUSNPlct-E',
    appId: '1:1068678823968:ios:5887b01be3f1d7c8747c45',
    messagingSenderId: '1068678823968',
    projectId: 'quizapp-2cba3',
    storageBucket: 'quizapp-2cba3.appspot.com',
    iosBundleId: 'com.example.firstAppEwa.RunnerTests',
  );
}
